import { App, defineAsyncComponent } from 'vue'
// Import base components as async components
// Base components
const FwBaseButton = defineAsyncComponent(() => import('client/components/base/button.vue'))
const FwAiButton = defineAsyncComponent(() => import('client/components/base/ai-button.vue'))
const FwAiInput = defineAsyncComponent(() => import('client/components/base/ai-input.vue'))
const FwAiTextarea = defineAsyncComponent(() => import('client/components/base/ai-textarea.vue'))
const FwBaseBadge = defineAsyncComponent(() => import('client/components/base/badge.vue'))
const Checkbox = defineAsyncComponent(() => import('client/components/base/checkbox.vue'))
const Close = defineAsyncComponent(() => import('client/components/base/close.vue'))
const Divider = defineAsyncComponent(() => import('client/components/base/divider.vue'))
const ImageContainer = defineAsyncComponent(() => import('client/components/base/image-container.vue'))
const Input = defineAsyncComponent(() => import('client/components/base/input.vue'))
const Popover = defineAsyncComponent(() => import('client/components/base/popover.vue'))
const FwSelect = defineAsyncComponent(() => import('client/components/base/select.vue'))
const FwTable = defineAsyncComponent(() => import('client/components/base/table.vue'))
const Textarea = defineAsyncComponent(() => import('client/components/base/textarea.vue'))
const MenuButton = defineAsyncComponent(() => import('client/components/base/menu-button.vue'))
const Toggle = defineAsyncComponent(() => import('client/components/base/toggle.vue'))
const FrameBar = defineAsyncComponent(() => import('client/components/base/frame-bar.vue'))
const Tab = defineAsyncComponent(() => import('client/components/base/tab.vue'))
const Tooltip = defineAsyncComponent(() => import('client/components/base/tooltip.vue'))
const DraggableList = defineAsyncComponent(() => import('client/components/base/draggable-list.vue'))
const FwCapsule = defineAsyncComponent(() => import('client/components/base/capsule.vue'))
const FwRadio = defineAsyncComponent(() => import('client/components/base/radio.vue'))
const FwSkeletonAnimation = defineAsyncComponent(() => import('client/components/base/skeleton-animation.vue'))
const FwSliderInput = defineAsyncComponent(() => import('client/components/base/slider-input.vue'))
const FwResponsiveWrapper = defineAsyncComponent(() => import('client/components/base/responsive-wrapper.vue'))
const FwSvgImage = defineAsyncComponent(() => import('client/components/base/svg-image.vue'))
const FwEmptyUserProfileIcon = defineAsyncComponent(() => import('client/components/base/empty-user-profile-icon.vue'))
const FwMicroIcon = defineAsyncComponent(() => import('client/components/base/micro-icon.vue'))
const FwCarousel = defineAsyncComponent(() => import('client/components/base/carousel.vue'))

// Composite components
const Icon = defineAsyncComponent(() => import('client/components/icon/icon.vue'))
const FwTileButton = defineAsyncComponent(() => import('client/components/composite/tile-button.vue'))
const CheckboxItem = defineAsyncComponent(() => import('client/components/composite/checkbox-item.vue'))
const Switcher = defineAsyncComponent(() => import('client/components/composite/switcher.vue'))
const Loading = defineAsyncComponent(() => import('client/components/composite/loading.vue'))
const FwMemberItem = defineAsyncComponent(() => import('client/components/composite/member-item.vue'))
const FwPlanBadge = defineAsyncComponent(() => import('client/components/composite/plan-badge.vue'))
const FwMenuIconButton = defineAsyncComponent(() => import('client/components/composite/menu-icon-button.vue'))
const FwMenuPopover = defineAsyncComponent(() => import('client/components/composite/menu-popover.vue'))
const FwAccordion = defineAsyncComponent(() => import('client/components/composite/accordion.vue'))
const FwAiSelectModel = defineAsyncComponent(() => import('client/components/composite/ai-select-model.vue'))
export default {
  install(app: App) {
    // Base components
    app.component('FwButton', FwBaseButton)
    app.component('FwAiButton', FwAiButton)
    app.component('FwAiInput', FwAiInput)
    app.component('FwAiTextarea', FwAiTextarea)
    app.component('FwBadge', FwBaseBadge)
    app.component('FwCheckbox', Checkbox)
    app.component('FwClose', Close)
    app.component('FwDivider', Divider)
    app.component('FwImageContainer', ImageContainer)
    app.component('FwInput', Input)
    app.component('FwPopover', Popover)
    app.component('FwSelect', FwSelect)
    app.component('FwTable', FwTable)
    app.component('FwTextarea', Textarea)
    app.component('FwMenuButton', MenuButton)
    app.component('FwToggle', Toggle)
    app.component('FwFrameBar', FrameBar)
    app.component('FwTab', Tab)
    app.component('FwTooltip', Tooltip)
    app.component('FwDraggableList', DraggableList)
    app.component('FwCapsule', FwCapsule)
    app.component('FwRadio', FwRadio)
    app.component('FwSkeletonAnimation', FwSkeletonAnimation)
    app.component('FwSliderInput', FwSliderInput)
    app.component('FwResponsiveWrapper', FwResponsiveWrapper)
    app.component('FwSvgImage', FwSvgImage)
    app.component('FwEmptyUserProfileIcon', FwEmptyUserProfileIcon)
    app.component('FwMicroIcon', FwMicroIcon)
    app.component('FwCarousel', FwCarousel)

    // Composite components
    app.component('FwIcon', Icon)
    app.component('FwTileButton', FwTileButton)
    app.component('FwCheckboxItem', CheckboxItem)
    app.component('FwSwitcher', Switcher)
    app.component('FwLoading', Loading)
    app.component('FwMemberItem', FwMemberItem)
    app.component('FwPlanBadge', FwPlanBadge)
    app.component('FwMenuIconButton', FwMenuIconButton)
    app.component('FwMenuPopover', FwMenuPopover)
    app.component('FwAiSelectModel', FwAiSelectModel)
    app.component('FwAccordion', FwAccordion)
  },
}
