import { readFileSync, writeFileSync, mkdirSync } from 'fs'

const data = JSON.parse(readFileSync('./foundation.json', 'utf-8'))
const variablesData = JSON.parse(readFileSync('./component.json', 'utf-8'))

function nameToVar(name) {
  return name.replace(/\//g, '-').replace(/ /g, '-').replace(/_/g, '-').toLowerCase()
}

function stripPrefix(name, prefix) {
  return name.startsWith(prefix + '/') ? name.slice(prefix.length + 1) : name
}

const linesRoot = []
const linesLight = []
const linesDark = []

// ── 1. Color Palette（原始色板，作为所有颜色的基础）──
const paletteCol = data.collections.find(c => c.name === 'colorPalette')
const paletteMap = new Map()
for (const v of paletteCol.modes[0].variables) {
  if (!v.isAlias) {
    linesRoot.push(`  --palette-${nameToVar(v.name)}: ${v.value};`)
    paletteMap.set(v.name, v.value)
  }
}

// ── 1.5. Base Colors（基础颜色 alias）──
for (const v of paletteCol.modes[0].variables) {
  if (v.isAlias && v.name.startsWith('base/')) {
    const targetName = v.value.name
    const varName = `--palette-${nameToVar(v.name)}`
    const refVar = `var(--palette-${nameToVar(targetName)})`
    linesRoot.push(`  ${varName}: ${refVar};`)
  }
}

// ── 2. Spacing ──
const spacingCol = data.collections.find(c => c.name === 'spacing')
for (const v of spacingCol.modes[0].variables) {
  linesRoot.push(`  --spacing-${nameToVar(v.name)}: ${v.value}px;`)
}

// ── 3. Radius ──
const radiusCol = data.collections.find(c => c.name === 'radius')
for (const v of radiusCol.modes[0].variables) {
  linesRoot.push(`  --radius-${nameToVar(v.name)}: ${v.value}px;`)
}

// ── 4. Typography ──
const typoCol = data.collections.find(c => c.name === 'Typography')
for (const v of typoCol.modes[0].variables) {
  const t = v.value
  const base = `--typo-${nameToVar(v.name)}`
  const lhUnit = t.lineHeightUnit === 'PIXELS' ? 'px' : '%'
  const ls = t.letterSpacingUnit === 'PERCENT'
    ? `${t.letterSpacing}%`
    : `${t.letterSpacing}px`
  linesRoot.push(`  ${base}-size: ${t.fontSize}px;`)
  linesRoot.push(`  ${base}-lh: ${t.lineHeight}${lhUnit};`)
  linesRoot.push(`  ${base}-ls: ${ls};`)
}

// ── 5. Alias Token（Light / Dark）──
const aliasCol = variablesData.collections.find(c => c.name === 'Alias Token')
for (const mode of aliasCol.modes) {
  const target = mode.name === 'Light' ? linesLight : linesDark
  for (const v of mode.variables) {
    const cleanName = stripPrefix(v.name, 'color')
    const varName = `--color-${nameToVar(cleanName)}`
    const val = v.value
    if (typeof val === 'object' && val !== null) {
      target.push(`  ${varName}: var(--palette-${nameToVar(val.name)});`)
    } else {
      target.push(`  ${varName}: ${val};`)
    }
  }
}

// ── 6. Effects（Light / Dark）──
const effectsCol = variablesData.collections.find(c => c.name === 'Effects')
for (const mode of effectsCol.modes) {
  if (!['Light', 'Dark'].includes(mode.name)) continue
  const target = mode.name === 'Light' ? linesLight : linesDark
  for (const v of mode.variables) {
    if (!['color', 'number'].includes(v.type)) continue
    const varName = `--effect-${nameToVar(v.name)}`
    let val = v.value
    if (typeof val === 'object' && val !== null) {
      val = `var(--palette-${nameToVar(val.name)})`
    } else if (v.type === 'number') {
      val = `${val}px`
    }
    target.push(`  ${varName}: ${val};`)
  }
}

// ── 输出 CSS ──
const css = [
  '/* Auto-generated by build.mjs — do not edit manually */',
  '/* Source: foundation.json + component.json */',
  '',
  ':root {',
  ...linesRoot,
  '}',
  '',
  ':root, [data-theme="light"] {',
  ...linesLight,
  '}',
  '',
  '[data-theme="dark"] {',
  ...linesDark,
  '}',
].join('\n')

mkdirSync('./dist', { recursive: true })
writeFileSync('./dist/tokens.css', css, 'utf-8')

console.log(`✅ tokens.css generated`)
console.log(`   palette + spacing + radius + typography: ${linesRoot.length} variables`)
console.log(`   light theme: ${linesLight.length} variables`)
console.log(`   dark theme: ${linesDark.length} variables`)
